# Generated by Django 4.2.5 on 2023-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_departamento_norad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.CharField(choices=[('arroyo_naranjo', 'Arroyo Naranjo'), ('boyeros', 'Boyeros'), ('centro_habana', 'Centro Habana'), ('cerro', 'Cerro'), ('cotorro', 'Cotorro'), ('diez_de_octubre', 'Diez de Octubre'), ('guanabacoa', 'Guanabacoa'), ('habana_del_este', 'Habana del Este'), ('habana_vieja', 'Habana Vieja'), ('la_lisa', 'La Lisa'), ('marianao', 'Marianao'), ('plaza', 'Plaza de la Revolución'), ('regla', 'Regla'), ('san_miguel_del_padron', 'San Miguel del Padrón'), ('playa', 'Playa')], max_length=50),
        ),
    ]
