# Generated by Django 4.2.5 on 2023-10-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
                ('departamento_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='customUser.departamento')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_tramite', models.CharField(choices=[('II', 'Demanda'), ('I', 'Queja'), ('IV', 'Solicitud')], max_length=10)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('codificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('tiene_respuesta', models.BooleanField(default=False)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('conclusion_queja', models.CharField(blank=True, choices=[('CR', 'Con Razón'), ('CRP', 'Con Razón en Parte'), ('SR', 'Sin Razón')], max_length=3, null=True)),
                ('nivel_solucion', models.CharField(blank=True, choices=[('S', 'Solucionado'), ('SP', 'Solucionado en Parte'), ('SS', 'Sin Solución'), ('PS', 'Pendiente a Solución')], max_length=2, null=True)),
                ('departamento_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customUser.departamento')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
                ('departamento_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='customUser.departamento')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noRadicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('asunto', models.CharField(choices=[('108', 'Reparación y Construcciones (Núcleo Familiares)'), ('104', 'Permuta entre particulares y el Estado'), ('117', 'Sobre Funcionarios de la Vivienda'), ('106', 'Inversión y rehabilitación  de vivienda'), ('125', 'Construcciones ilegales (extracciones, demoliciones, etc.))'), ('102', 'Ampliación'), ('120', 'Afectaciones del Estado o Particulares'), ('122', 'Ocupaciones ilegales (no incluye las construcciones autorizadas)'), ('107', 'Materiales de Construcción (Comisión de distribución  expendedores, etc.)'), ('105', 'Albergue'), ('121', 'Vivienda vinculadas y medios básicos (No incluye los consultorios MF)'), ('113', 'Litigios (Reclamaciones de derechos sobre inmuebles, límite de terreno, uso de área común entre particulares y el Estado)'), ('111', 'Incorporación a Micro brigadas, Bajo  Costo o Esfuerzo Propio'), ('126', 'Arrendamiento  en moneda nacional o libremente convertible)'), ('110', 'Crédito'), ('123', 'Inmigración Interna (Decreto ley 217)'), ('114', 'Solares'), ('116', 'Legalización de vivienda y solares'), ('130', 'Otros asuntos'), ('128', 'Funcionamiento del Arquitecto de la Comunidad'), ('118', 'Ley  General de la Vivienda (Consultas, críticas, sugerencias)'), ('127', 'Licencia para nuevas construcciones'), ('129', 'Sobre trabajadores, dirigentes y funcionarios'), ('101', 'Inmuebles (Casa, apartamento, ciudadelas, etc.)'), ('124', 'Confiscaciones)'), ('103', 'Permuta entre particulares'), ('115', 'Compra y venta (Ilegalidades)'), ('119', 'Comisiones de Asignación de viviendas'), ('109', 'Reparación y Construcciones colectiva Edificios multifamiliares, ciudadelas, etc.)'), ('112', 'Movimiento de Micro brigada')], max_length=200)),
                ('municipio', models.CharField(choices=[('arroyo_naranjo', 'Arroyo Naranjo'), ('boyeros', 'Boyeros'), ('centro_habana', 'Centro Habana'), ('cerro', 'Cerro'), ('cotorro', 'Cotorro'), ('diez_de_octubre', 'Diez de Octubre'), ('guanabacoa', 'Guanabacoa'), ('habana_del_este', 'Habana del Este'), ('habana_vieja', 'Habana Vieja'), ('la_lisa', 'La Lisa'), ('mantilla', 'Mantilla'), ('marianao', 'Marianao'), ('playa', 'Playa'), ('plaza', 'Plaza de la Revolución'), ('regla', 'Regla'), ('san_miguel_del_padron', 'San Miguel del Padrón')], max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('departamento_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quejas', to='customUser.departamento')),
                ('organismo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='customUser.organismo')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siapdpv.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.demanda')),
                ('queja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.queja')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.solicitud')),
            ],
        ),
    ]
