# Generated by Django 4.2.5 on 2023-09-20 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('usuarios', models.ManyToManyField(blank=True, null=True, related_name='departamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('usuarios', models.ManyToManyField(blank=True, null=True, related_name='organismos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('queja', 'Queja'), ('demanda', 'Demanda'), ('solicitud', 'Solicitud')], max_length=10)),
                ('aprobado', models.BooleanField(default=False)),
                ('departamento_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siapdpv.departamento')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
                ('departamento_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='siapdpv.departamento')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('procesado', models.BooleanField(default=False)),
                ('enTramite', models.BooleanField(default=False)),
                ('departamento_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quejas', to='siapdpv.departamento')),
                ('organismo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='siapdpv.organismo')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.demanda')),
                ('queja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.queja')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.demanda')),
                ('queja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.queja')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siapdpv.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='departamento_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='siapdpv.departamento'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='recurrente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
