# Generated by Django 4.2.5 on 2023-09-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='municipio',
            field=models.CharField(choices=[('arroyo_naranjo', 'Arroyo Naranjo'), ('boyeros', 'Boyeros'), ('centro_habana', 'Centro Habana'), ('cerro', 'Cerro'), ('cotorro', 'Cotorro'), ('diez_de_octubre', 'Diez de Octubre'), ('guanabacoa', 'Guanabacoa'), ('habana_del_este', 'Habana del Este'), ('habana_vieja', 'Habana Vieja'), ('la_lisa', 'La Lisa'), ('mantilla', 'Mantilla'), ('marianao', 'Marianao'), ('playa', 'Playa'), ('plaza', 'Plaza de la Revolución'), ('regla', 'Regla'), ('san_miguel_del_padron', 'San Miguel del Padrón')], max_length=100),
        ),
    ]
