# Generated by Django 4.2.5 on 2023-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='asunto',
            field=models.CharField(choices=[('129', 'Sobre trabajadores, dirigentes y funcionarios'), ('101', 'Inmuebles (Casa, apartamento, ciudadelas, etc.)'), ('122', 'Ocupaciones ilegales (no incluye las construcciones autorizadas)'), ('117', 'Sobre Funcionarios de la Vivienda'), ('113', 'Litigios (Reclamaciones de derechos sobre inmuebles, límite de terreno, uso de área común entre particulares y el Estado)'), ('106', 'Inversión y rehabilitación  de vivienda'), ('115', 'Compra y venta (Ilegalidades)'), ('105', 'Albergue'), ('123', 'Inmigración Interna (Decreto ley 217)'), ('110', 'Crédito'), ('114', 'Solares'), ('120', 'Afectaciones del Estado o Particulares'), ('125', 'Construcciones ilegales (extracciones, demoliciones, etc.))'), ('103', 'Permuta entre particulares'), ('104', 'Permuta entre particulares y el Estado'), ('107', 'Materiales de Construcción (Comisión de distribución  expendedores, etc.)'), ('127', 'Licencia para nuevas construcciones'), ('112', 'Movimiento de Micro brigada'), ('121', 'Vivienda vinculadas y medios básicos (No incluye los consultorios MF)'), ('109', 'Reparación y Construcciones colectiva Edificios multifamiliares, ciudadelas, etc.)'), ('126', 'Arrendamiento  en moneda nacional o libremente convertible)'), ('102', 'Ampliación'), ('116', 'Legalización de vivienda y solares'), ('118', 'Ley  General de la Vivienda (Consultas, críticas, sugerencias)'), ('128', 'Funcionamiento del Arquitecto de la Comunidad'), ('111', 'Incorporación a Micro brigadas, Bajo  Costo o Esfuerzo Propio'), ('124', 'Confiscaciones)'), ('119', 'Comisiones de Asignación de viviendas'), ('108', 'Reparación y Construcciones (Núcleo Familiares)'), ('130', 'Otros asuntos')], max_length=200),
        ),
    ]
