# Generated by Django 4.2.5 on 2023-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='respuesta',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
