# Generated by Django 4.2.5 on 2023-10-09 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0002_tramite_adjunto_tramite_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
