# Generated by Django 4.2.5 on 2023-10-04 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0002_queja_descripcion_alter_queja_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='queja',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
