# Generated by Django 4.2.5 on 2023-10-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0003_tramite_fecha_creacion_tramite_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siapdpv.tramite'),
        ),
    ]
