# Generated by Django 4.2.5 on 2023-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0004_queja_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='noRadicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
