# Generated by Django 4.2.5 on 2023-10-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0005_queja_noradicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='conclusion_queja',
            field=models.CharField(blank=True, choices=[('CR', 'Con Razón'), ('CRP', 'Con Razón en Parte'), ('SR', 'Sin Razón')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='nivel_solucion',
            field=models.CharField(blank=True, choices=[('S', 'Solucionado'), ('SP', 'Solucionado en Parte'), ('SS', 'Sin Solución'), ('PS', 'Pendiente a Solución')], max_length=2, null=True),
        ),
    ]
