# Generated by Django 4.2.5 on 2023-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siapdpv', '0007_tramite_tiene_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='codificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='asunto',
            field=models.CharField(choices=[('101', 'Inmuebles (Casa, apartamento, ciudadelas, etc.)'), ('103', 'Permuta entre particulares'), ('102', 'Ampliación')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(choices=[('I', 'Queja'), ('II', 'Demanda'), ('IV', 'Solicitud')], max_length=10),
        ),
    ]
